version: "3"
services:
  python3:
    build:
      dockerfile: Dockerfile
    container_name: "python3"
    tty: true
    privileged: true
    volumes:
      - /Volumes/kamiyaSSDX5/DockerVolume/python/git:/home/kamiken/git
      - /Volumes/kamiyaSSDX5/DockerVolume/python/polo-sdk-python:/home/kamiken/polo_sdk
      - /Volumes/kamiyaSSDX5/DockerVolume/kafka:/home/kamiken/kafka
      - /Volumes/kamiyaSSDX5/DockerVolume/spark:/home/kamiken/spark
    networks:
      shared-network:
        ipv4_address: 172.29.0.9
    ports:
      - '21022:22'
    deploy:
      resources:
        limits:
          cpus: '1.0'

networks:
  shared-network:
    external: true
