version: "3"
services:
  python3:
    build:
      dockerfile: Dockerfile
    init : true
    container_name: "python3"
    hostname: python3
    tty: true
    privileged: true
    volumes:
      - ${GIT_HOME}:/home/${PYUSER}/git
      - ${DOCKER_VOLUME_HOME}/kafka:/home/${PYUSER}/kafka
      - ${DOCKER_VOLUME_HOME}/python_packages/polo-sdk-python:/home/polo_sdk
    networks:
      shared-network:
        ipv4_address: ${PYTHON_HOST}
    ports:
      - '30022:22'
      - '8890:8888'

networks:
  shared-network:
    external: true
