version: "3"
services:
    hive-client:
        build:
            dockerfile: Dockerfile
        image: hive-client
        container_name: hive-client
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://172.30.0.9/metastore"
        ports:
            - 11000:10000
            - 11002:10002
        env_file:
            - ./hadoop.env
        networks:
            shared-network:
                ipv4_address: 172.30.0.15

networks:
    shared-network:
        external: true
