version: '3.7'
services:
  trino:
    build:
      dockerfile: Dockerfile
    hostname: trino
    container_name: trino
    ports:
      - '8881:8080'
      - '22022:22'
    volumes:
      - ${TRINO_VOLUME_HOME}/trino/etc:/etc/trino
      - ${HADOOP_CONF}:/etc/hadoop
    networks:
      shared-network:
        ipv4_address: 172.30.0.2

networks:
  shared-network:
    external: true
