version: "3.9"
services:
  mysql:
    build: ./mysql/ #Dockerfileのパス
    ports:
      - "13306:3306" #ホストの13306番ポートとコンテナの3306番ポートをマッピング
    volumes:
      #- ./mysql/db:/docker-entrypoint-initdb.d #初期データをマウントする場所
      - ${MYSQL_HOME}:/var/lib/mysql
    image: mysql:8.0.31 #イメージ名
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    networks:
      - shared-network
networks:
  shared-network:
    external: true
