version: '3.7'
services:
  cassandra1:
    image: cassandra:4.1.0
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data1:/var/lib/cassandra
      - ${CASSANDRA_HOME1}/etc:/etc/cassandra
    networks:
      shared-network:
        ipv4_address: ${CASSANDRA_HOST1}
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2" # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_LISTEN_ADDRESS: ${CASSANDRA_HOST1}
      CASSANDRA_BROADCAST_ADDRESS: ${CASSANDRA_HOST1}
      CASSANDRA_BROADCAST_RPC_ADDRESS: ${LOCAL_HOST} # Need to use Host IP address to access from external hosts.
      CASSANDRA_NATIVE_TRANSPORT_PORT: 9042
      HEAP_NEWSIZE: 1G
      MAX_HEAP_SIZE: 2G

  cassandra2:
    image: cassandra:4.1.0
    container_name: cassandra2
    hostname: cassandra2
    networks:
      shared-network:
        ipv4_address: ${CASSANDRA_HOST2}
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2" # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_LISTEN_ADDRESS: ${CASSANDRA_HOST2}
      CASSANDRA_BROADCAST_ADDRESS: ${CASSANDRA_HOST2}
      CASSANDRA_BROADCAST_RPC_ADDRESS: ${LOCAL_HOST} # Need to use Host IP address to access from external hosts.
      CASSANDRA_NATIVE_TRANSPORT_PORT: 9043
      HEAP_NEWSIZE: 1G
      MAX_HEAP_SIZE: 2G
    ports:
      - "9043:9043"
    volumes:
      - cassandra_data2:/var/lib/cassandra
      - ${CASSANDRA_HOME2}/etc:/etc/cassandra
    depends_on:
      - cassandra1

  cassandra3:
    image: cassandra:4.1.0
    container_name: cassandra3
    hostname: cassandra3
    networks:
      shared-network:
        ipv4_address: ${CASSANDRA_HOST3}
    environment:
      CASSANDRA_SEEDS: "cassandra1,cassandra2" # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_LISTEN_ADDRESS: ${CASSANDRA_HOST3}
      CASSANDRA_BROADCAST_ADDRESS: ${CASSANDRA_HOST3}
      CASSANDRA_BROADCAST_RPC_ADDRESS: ${LOCAL_HOST} # Need to use Host IP address to access from external hosts.
      CASSANDRA_NATIVE_TRANSPORT_PORT: 9044
      HEAP_NEWSIZE: 1G
      MAX_HEAP_SIZE: 2G
    ports:
      - "9044:9044"
    volumes:
      - cassandra_data3:/var/lib/cassandra
      - ${CASSANDRA_HOME3}/etc:/etc/cassandra
    depends_on:
      - cassandra2

volumes:
    cassandra_data1:
      external: true
    cassandra_data2:
      external: true
    cassandra_data3:
      external: true

networks:
  shared-network:
    external: true
